### ISSUE TITLE
Kindly invite me to the organization

### ISSUE THREAD

**Issue by Susmita-Dey** [Thalassa-Ta/Join-the-organization#1]
I've starred the repository. Kindly invite me to the organization. 
I came to know from my friend's github profile.
I would like to join so that I can help the community, improve and learn in public.
Thank you

**Comment by thuongtruong1009** [comment]
@Susmita-Dey !
Welcome to the organization!
Let's contribute to the growing community.
Accept our invitation and you are a full member.
Thank you!
