### ISSUE TITLE
Please invite me your community

### ISSUE THREAD

**Issue by Astro2020-lovely** [Thalassa-Ta/Join-the-organization#4]
Please invite me your community

**Comment by thuongtruong1009** [comment]
> Please invite me your community

@Astro2020-lovely 
Welcome to the organization!
Let's contribute to the growing community.
I have sent you an invitation via email. Accept it and you are a full member.
Thank you!

![image](https://user-images.githubusercontent.com/71834167/166106099-fbfacfbf-3442-4e87-9397-392768c9cd1d.png)
